#
# Builds the docs and deploys to GitHub pages
#
# Using https://github.com/marketplace/actions/deploy-to-github-pages
name: Docs Build & Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "npm"
      - run: npm ci
      - run: npm test
      - run: npm run build:docs
      - name: Deploy Docs 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: docs
